from PyQt5 import QtCore, QtGui, QtWidgets
import pathlib


folder_images_path = pathlib.Path(__file__).parent.parent.joinpath("Images")
class Ui_exercises_scene(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("border-top-left-radius: 15px;\n"
"border-bottom-left-radius: 15px;\n"
"border-top-right-radius: 15px;\n"
"border-bottom-right-radius: 15px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_level_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_level_1.setGeometry(QtCore.QRect(150, 100, 300, 350))
        self.frame_level_1.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.frame_level_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_level_1.setFrameShadow(QtWidgets.QFrame.Raised)
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(50)
        self.frame_level_1.setGraphicsEffect(shadow)
        self.frame_level_1.setObjectName("frame_level_1")
        self.image_level_1 = QtWidgets.QLabel(self.frame_level_1)
        self.image_level_1.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.image_level_1.setText("")
        self.image_level_1.setPixmap(QtGui.QPixmap(
                folder_images_path.joinpath("уровень1.jpg").__str__()))
        self.image_level_1.setObjectName("image_level_1")
        self.name_level_1 = QtWidgets.QLabel(self.frame_level_1)
        self.name_level_1.setGeometry(QtCore.QRect(50, 120, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.name_level_1.setFont(font)
        self.name_level_1.setStyleSheet("color: rgb(42, 85, 126);\n"
"background-color: rgb(255, 177, 125);")
        self.name_level_1.setAlignment(QtCore.Qt.AlignCenter)
        self.name_level_1.setObjectName("name_level_1")
        self.stat_level_1 = QtWidgets.QFrame(self.frame_level_1)
        self.stat_level_1.setGeometry(QtCore.QRect(10, 229, 280, 111))
        self.stat_level_1.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.stat_level_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stat_level_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stat_level_1.setObjectName("stat_level_1")
        self.spedd_level_1 = QtWidgets.QLabel(self.stat_level_1)
        self.spedd_level_1.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.spedd_level_1.setFont(font)
        self.spedd_level_1.setStyleSheet("color: rgb(39, 117, 117);")
        self.spedd_level_1.setObjectName("spedd_level_1")
        self.count_accuracy_level_1 = QtWidgets.QProgressBar(self.stat_level_1)
        self.count_accuracy_level_1.setGeometry(QtCore.QRect(180, 70, 81, 23))
        self.count_accuracy_level_1.setStyleSheet("QProgressBar{\n"
"    color: rgb(255, 180, 130);\n"
"    border: 1px solid  grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(39, 117, 117);;\n"
"    border-radius: 3px;\n"
"}")
        self.count_accuracy_level_1.setProperty("value", 75)
        self.count_accuracy_level_1.setAlignment(QtCore.Qt.AlignCenter)
        self.count_accuracy_level_1.setOrientation(QtCore.Qt.Horizontal)
        self.count_accuracy_level_1.setFormat("%p%")
        self.count_accuracy_level_1.setObjectName("count_accuracy_level_1")
        self.accuracy_level_1 = QtWidgets.QLabel(self.stat_level_1)
        self.accuracy_level_1.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.accuracy_level_1.setFont(font)
        self.accuracy_level_1.setStyleSheet("color: rgb(39, 117, 117);")
        self.accuracy_level_1.setObjectName("accuracy_level_1")
        self.count_spedd_level_1 = QtWidgets.QLineEdit(self.stat_level_1)
        self.count_spedd_level_1.setGeometry(QtCore.QRect(180, 10, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.count_spedd_level_1.setFont(font)
        self.count_spedd_level_1.setStyleSheet("color: rgb(40, 120, 120);")
        self.count_spedd_level_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_spedd_level_1.setReadOnly(True)
        self.count_spedd_level_1.setObjectName("count_spedd_level_1")
        self.symbols_in_minute_level_1 = QtWidgets.QLabel(self.stat_level_1)
        self.symbols_in_minute_level_1.setGeometry(QtCore.QRect(210, 21, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.symbols_in_minute_level_1.setFont(font)
        self.symbols_in_minute_level_1.setStyleSheet("color: rgba(39, 117, 117, 120);")
        self.symbols_in_minute_level_1.setObjectName("symbols_in_minute_level_1")
        self.separator_level_1 = QtWidgets.QFrame(self.frame_level_1)
        self.separator_level_1.setGeometry(QtCore.QRect(10, 210, 280, 1))
        self.separator_level_1.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.separator_level_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_level_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_level_1.setObjectName("separator_level_1")
        self.button_level_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_level_1.setGeometry(QtCore.QRect(150, 100, 300, 350))
        self.button_level_1.setStyleSheet("QPushButton::hover{background-color : rgba(250, 250, 250, 30);}")
        self.button_level_1.setText("")
        self.button_level_1.setObjectName("button_level_1")
        self.frame_level_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_level_2.setGeometry(QtCore.QRect(480, 100, 300, 350))
        self.frame_level_2.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.frame_level_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_level_2.setFrameShadow(QtWidgets.QFrame.Raised)
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(50)
        self.frame_level_2.setGraphicsEffect(shadow)
        self.frame_level_2.setObjectName("frame_level_2")
        self.image_level_2 = QtWidgets.QLabel(self.frame_level_2)
        self.image_level_2.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.image_level_2.setText("")
        self.image_level_2.setPixmap(QtGui.QPixmap(
                folder_images_path.joinpath("уровень2.jpg").__str__()))
        self.image_level_2.setObjectName("image_level_2")
        self.name_level_2 = QtWidgets.QLabel(self.frame_level_2)
        self.name_level_2.setGeometry(QtCore.QRect(50, 120, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.name_level_2.setFont(font)
        self.name_level_2.setStyleSheet("color: rgb(42, 85, 126);\n"
"background-color: rgb(255, 177, 125);")
        self.name_level_2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_level_2.setObjectName("name_level_2")
        self.stat_level_2 = QtWidgets.QFrame(self.frame_level_2)
        self.stat_level_2.setGeometry(QtCore.QRect(10, 229, 280, 111))
        self.stat_level_2.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.stat_level_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stat_level_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stat_level_2.setObjectName("stat_level_2")
        self.spedd_level_2 = QtWidgets.QLabel(self.stat_level_2)
        self.spedd_level_2.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.spedd_level_2.setFont(font)
        self.spedd_level_2.setStyleSheet("color: rgb(39, 117, 117);")
        self.spedd_level_2.setObjectName("spedd_level_2")
        self.count_accuracy_level_2 = QtWidgets.QProgressBar(self.stat_level_2)
        self.count_accuracy_level_2.setGeometry(QtCore.QRect(180, 70, 81, 23))
        self.count_accuracy_level_2.setStyleSheet("QProgressBar{\n"
"    color: rgb(255, 180, 130);\n"
"    border: 1px solid  grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(39, 117, 117);;\n"
"    border-radius: 3px;\n"
"}")
        self.count_accuracy_level_2.setProperty("value", 75)
        self.count_accuracy_level_2.setAlignment(QtCore.Qt.AlignCenter)
        self.count_accuracy_level_2.setOrientation(QtCore.Qt.Horizontal)
        self.count_accuracy_level_2.setFormat("%p%")
        self.count_accuracy_level_2.setObjectName("count_accuracy_level_2")
        self.accuracy_level_2 = QtWidgets.QLabel(self.stat_level_2)
        self.accuracy_level_2.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.accuracy_level_2.setFont(font)
        self.accuracy_level_2.setStyleSheet("color: rgb(39, 117, 117);")
        self.accuracy_level_2.setObjectName("accuracy_level_2")
        self.count_spedd_level_2 = QtWidgets.QLineEdit(self.stat_level_2)
        self.count_spedd_level_2.setGeometry(QtCore.QRect(180, 10, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.count_spedd_level_2.setFont(font)
        self.count_spedd_level_2.setStyleSheet("color: rgb(40, 120, 120);")
        self.count_spedd_level_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_spedd_level_2.setReadOnly(True)
        self.count_spedd_level_2.setObjectName("count_spedd_level_2")
        self.symbols_in_minute_level_2 = QtWidgets.QLabel(self.stat_level_2)
        self.symbols_in_minute_level_2.setGeometry(QtCore.QRect(210, 21, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.symbols_in_minute_level_2.setFont(font)
        self.symbols_in_minute_level_2.setStyleSheet("color: rgba(39, 117, 117, 120);")
        self.symbols_in_minute_level_2.setObjectName("symbols_in_minute_level_2")
        self.separator_level_2 = QtWidgets.QFrame(self.frame_level_2)
        self.separator_level_2.setGeometry(QtCore.QRect(10, 210, 280, 1))
        self.separator_level_2.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.separator_level_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_level_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_level_2.setObjectName("separator_level_2")
        self.button_level_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_level_2.setGeometry(QtCore.QRect(480, 100, 300, 350))
        self.button_level_2.setStyleSheet("QPushButton::hover{background-color : rgba(250, 250, 250, 30);}")
        self.button_level_2.setText("")
        self.button_level_2.setObjectName("button_level_2")
        self.frame_level_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_level_3.setGeometry(QtCore.QRect(810, 100, 300, 350))
        self.frame_level_3.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.frame_level_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_level_3.setFrameShadow(QtWidgets.QFrame.Raised)
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(50)
        self.frame_level_3.setGraphicsEffect(shadow)
        self.frame_level_3.setObjectName("frame_level_3")
        self.image_level_3 = QtWidgets.QLabel(self.frame_level_3)
        self.image_level_3.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.image_level_3.setText("")
        self.image_level_3.setPixmap(QtGui.QPixmap(
                folder_images_path.joinpath("уровень3.png").__str__()))
        self.image_level_3.setObjectName("image_level_3")
        self.name_level_3 = QtWidgets.QLabel(self.frame_level_3)
        self.name_level_3.setGeometry(QtCore.QRect(50, 120, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.name_level_3.setFont(font)
        self.name_level_3.setStyleSheet("color: rgb(42, 85, 126);\n"
"background-color: rgb(255, 177, 125);")
        self.name_level_3.setAlignment(QtCore.Qt.AlignCenter)
        self.name_level_3.setObjectName("name_level_3")
        self.stat_level_3 = QtWidgets.QFrame(self.frame_level_3)
        self.stat_level_3.setGeometry(QtCore.QRect(10, 229, 280, 111))
        self.stat_level_3.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.stat_level_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stat_level_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stat_level_3.setObjectName("stat_level_3")
        self.spedd_level_3 = QtWidgets.QLabel(self.stat_level_3)
        self.spedd_level_3.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.spedd_level_3.setFont(font)
        self.spedd_level_3.setStyleSheet("color: rgb(39, 117, 117);")
        self.spedd_level_3.setObjectName("spedd_level_3")
        self.count_accuracy_level_3 = QtWidgets.QProgressBar(self.stat_level_3)
        self.count_accuracy_level_3.setGeometry(QtCore.QRect(180, 70, 81, 23))
        self.count_accuracy_level_3.setStyleSheet("QProgressBar{\n"
"    color: rgb(255, 180, 130);\n"
"    border: 1px solid  grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(39, 117, 117);;\n"
"    border-radius: 3px;\n"
"}")
        self.count_accuracy_level_3.setProperty("value", 75)
        self.count_accuracy_level_3.setAlignment(QtCore.Qt.AlignCenter)
        self.count_accuracy_level_3.setOrientation(QtCore.Qt.Horizontal)
        self.count_accuracy_level_3.setFormat("%p%")
        self.count_accuracy_level_3.setObjectName("count_accuracy_level_3")
        self.accuracy_level_3 = QtWidgets.QLabel(self.stat_level_3)
        self.accuracy_level_3.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.accuracy_level_3.setFont(font)
        self.accuracy_level_3.setStyleSheet("color: rgb(39, 117, 117);")
        self.accuracy_level_3.setObjectName("accuracy_level_3")
        self.count_spedd_level_3 = QtWidgets.QLineEdit(self.stat_level_3)
        self.count_spedd_level_3.setGeometry(QtCore.QRect(180, 10, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.count_spedd_level_3.setFont(font)
        self.count_spedd_level_3.setStyleSheet("color: rgb(40, 120, 120);")
        self.count_spedd_level_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_spedd_level_3.setReadOnly(True)
        self.count_spedd_level_3.setObjectName("count_spedd_level_3")
        self.symbols_in_minute_level_3 = QtWidgets.QLabel(self.stat_level_3)
        self.symbols_in_minute_level_3.setGeometry(QtCore.QRect(210, 21, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.symbols_in_minute_level_3.setFont(font)
        self.symbols_in_minute_level_3.setStyleSheet("color: rgba(39, 117, 117, 120);")
        self.symbols_in_minute_level_3.setObjectName("symbols_in_minute_level_3")
        self.separator_level_3 = QtWidgets.QFrame(self.frame_level_3)
        self.separator_level_3.setGeometry(QtCore.QRect(10, 210, 280, 1))
        self.separator_level_3.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.separator_level_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_level_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_level_3.setObjectName("separator_level_3")
        self.button_level_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_level_3.setGeometry(QtCore.QRect(810, 100, 300, 350))
        self.button_level_3.setStyleSheet("QPushButton::hover{background-color : rgba(250, 250, 250, 30);}")
        self.button_level_3.setText("")
        self.button_level_3.setObjectName("button_level_3")
        self.frame_level_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_level_4.setGeometry(QtCore.QRect(1140, 100, 300, 350))
        self.frame_level_4.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.frame_level_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_level_4.setFrameShadow(QtWidgets.QFrame.Raised)
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(50)
        self.frame_level_4.setGraphicsEffect(shadow)
        self.frame_level_4.setObjectName("frame_level_4")
        self.image_level_4 = QtWidgets.QLabel(self.frame_level_4)
        self.image_level_4.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.image_level_4.setText("")
        self.image_level_4.setPixmap(QtGui.QPixmap(
                folder_images_path.joinpath("уровень4.jpg").__str__()))
        self.image_level_4.setObjectName("image_level_4")
        self.name_level_4 = QtWidgets.QLabel(self.frame_level_4)
        self.name_level_4.setGeometry(QtCore.QRect(50, 120, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.name_level_4.setFont(font)
        self.name_level_4.setStyleSheet("color: rgb(42, 85, 126);\n"
"background-color: rgb(255, 177, 125);")
        self.name_level_4.setAlignment(QtCore.Qt.AlignCenter)
        self.name_level_4.setObjectName("name_level_4")
        self.stat_level_4 = QtWidgets.QFrame(self.frame_level_4)
        self.stat_level_4.setGeometry(QtCore.QRect(10, 229, 280, 111))
        self.stat_level_4.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.stat_level_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stat_level_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stat_level_4.setObjectName("stat_level_4")
        self.spedd_level_4 = QtWidgets.QLabel(self.stat_level_4)
        self.spedd_level_4.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.spedd_level_4.setFont(font)
        self.spedd_level_4.setStyleSheet("color: rgb(39, 117, 117);")
        self.spedd_level_4.setObjectName("spedd_level_4")
        self.count_accuracy_level_4 = QtWidgets.QProgressBar(self.stat_level_4)
        self.count_accuracy_level_4.setGeometry(QtCore.QRect(180, 70, 81, 23))
        self.count_accuracy_level_4.setStyleSheet("QProgressBar{\n"
"    color: rgb(255, 180, 130);\n"
"    border: 1px solid  grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(39, 117, 117);;\n"
"    border-radius: 3px;\n"
"}")
        self.count_accuracy_level_4.setProperty("value", 75)
        self.count_accuracy_level_4.setAlignment(QtCore.Qt.AlignCenter)
        self.count_accuracy_level_4.setOrientation(QtCore.Qt.Horizontal)
        self.count_accuracy_level_4.setFormat("%p%")
        self.count_accuracy_level_4.setObjectName("count_accuracy_level_4")
        self.accuracy_level_4 = QtWidgets.QLabel(self.stat_level_4)
        self.accuracy_level_4.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.accuracy_level_4.setFont(font)
        self.accuracy_level_4.setStyleSheet("color: rgb(39, 117, 117);")
        self.accuracy_level_4.setObjectName("accuracy_level_4")
        self.count_spedd_level_4 = QtWidgets.QLineEdit(self.stat_level_4)
        self.count_spedd_level_4.setGeometry(QtCore.QRect(180, 10, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.count_spedd_level_4.setFont(font)
        self.count_spedd_level_4.setStyleSheet("color: rgb(40, 120, 120);")
        self.count_spedd_level_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_spedd_level_4.setReadOnly(True)
        self.count_spedd_level_4.setObjectName("count_spedd_level_4")
        self.symbols_in_minute_level_4 = QtWidgets.QLabel(self.stat_level_4)
        self.symbols_in_minute_level_4.setGeometry(QtCore.QRect(210, 21, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.symbols_in_minute_level_4.setFont(font)
        self.symbols_in_minute_level_4.setStyleSheet("color: rgba(39, 117, 117, 120);")
        self.symbols_in_minute_level_4.setObjectName("symbols_in_minute_level_4")
        self.separator_level_4 = QtWidgets.QFrame(self.frame_level_4)
        self.separator_level_4.setGeometry(QtCore.QRect(10, 210, 280, 1))
        self.separator_level_4.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.separator_level_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_level_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_level_4.setObjectName("separator_level_4")
        self.button_level_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_level_4.setGeometry(QtCore.QRect(1140, 100, 300, 350))
        self.button_level_4.setStyleSheet("QPushButton::hover{background-color : rgba(250, 250, 250, 30);}")
        self.button_level_4.setText("")
        self.button_level_4.setObjectName("button_level_4")
        self.frame_level_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_level_5.setGeometry(QtCore.QRect(1470, 100, 300, 350))
        self.frame_level_5.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.frame_level_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_level_5.setFrameShadow(QtWidgets.QFrame.Raised)
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(50)
        self.frame_level_5.setGraphicsEffect(shadow)
        self.frame_level_5.setObjectName("frame_level_5")
        self.image_level_5 = QtWidgets.QLabel(self.frame_level_5)
        self.image_level_5.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.image_level_5.setText("")
        self.image_level_5.setPixmap(QtGui.QPixmap(
                folder_images_path.joinpath("уровень5.jpg").__str__()))
        self.image_level_5.setObjectName("image_level_5")
        self.name_level_5 = QtWidgets.QLabel(self.frame_level_5)
        self.name_level_5.setGeometry(QtCore.QRect(50, 120, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.name_level_5.setFont(font)
        self.name_level_5.setStyleSheet("color: rgb(42, 85, 126);\n"
"background-color: rgb(255, 177, 125);")
        self.name_level_5.setAlignment(QtCore.Qt.AlignCenter)
        self.name_level_5.setObjectName("name_level_5")
        self.stat_level_5 = QtWidgets.QFrame(self.frame_level_5)
        self.stat_level_5.setGeometry(QtCore.QRect(10, 229, 280, 111))
        self.stat_level_5.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.stat_level_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stat_level_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stat_level_5.setObjectName("stat_level_5")
        self.spedd_level_5 = QtWidgets.QLabel(self.stat_level_5)
        self.spedd_level_5.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.spedd_level_5.setFont(font)
        self.spedd_level_5.setStyleSheet("color: rgb(39, 117, 117);")
        self.spedd_level_5.setObjectName("spedd_level_5")
        self.count_accuracy_level_5 = QtWidgets.QProgressBar(self.stat_level_5)
        self.count_accuracy_level_5.setGeometry(QtCore.QRect(180, 70, 81, 23))
        self.count_accuracy_level_5.setStyleSheet("QProgressBar{\n"
"    color: rgb(255, 180, 130);\n"
"    border: 1px solid  grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(39, 117, 117);;\n"
"    border-radius: 3px;\n"
"}")
        self.count_accuracy_level_5.setProperty("value", 75)
        self.count_accuracy_level_5.setAlignment(QtCore.Qt.AlignCenter)
        self.count_accuracy_level_5.setOrientation(QtCore.Qt.Horizontal)
        self.count_accuracy_level_5.setFormat("%p%")
        self.count_accuracy_level_5.setObjectName("count_accuracy_level_5")
        self.accuracy_level_5 = QtWidgets.QLabel(self.stat_level_5)
        self.accuracy_level_5.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.accuracy_level_5.setFont(font)
        self.accuracy_level_5.setStyleSheet("color: rgb(39, 117, 117);")
        self.accuracy_level_5.setObjectName("accuracy_level_5")
        self.count_spedd_level_5 = QtWidgets.QLineEdit(self.stat_level_5)
        self.count_spedd_level_5.setGeometry(QtCore.QRect(180, 10, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.count_spedd_level_5.setFont(font)
        self.count_spedd_level_5.setStyleSheet("color: rgb(40, 120, 120);")
        self.count_spedd_level_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_spedd_level_5.setReadOnly(True)
        self.count_spedd_level_5.setObjectName("count_spedd_level_5")
        self.symbols_in_minute_level_5 = QtWidgets.QLabel(self.stat_level_5)
        self.symbols_in_minute_level_5.setGeometry(QtCore.QRect(210, 21, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.symbols_in_minute_level_5.setFont(font)
        self.symbols_in_minute_level_5.setStyleSheet("color: rgba(39, 117, 117, 120);")
        self.symbols_in_minute_level_5.setObjectName("symbols_in_minute_level_5")
        self.separator_level_5 = QtWidgets.QFrame(self.frame_level_5)
        self.separator_level_5.setGeometry(QtCore.QRect(10, 210, 280, 1))
        self.separator_level_5.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.separator_level_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_level_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_level_5.setObjectName("separator_level_5")
        self.button_level_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_level_5.setGeometry(QtCore.QRect(1470, 100, 300, 350))
        self.button_level_5.setStyleSheet("QPushButton::hover{background-color : rgba(250, 250, 250, 30);}")
        self.button_level_5.setText("")
        self.button_level_5.setObjectName("button_level_5")
        self.frame_level_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_level_6.setGeometry(QtCore.QRect(150, 500, 300, 350))
        self.frame_level_6.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.frame_level_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_level_6.setFrameShadow(QtWidgets.QFrame.Raised)
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(50)
        self.frame_level_6.setGraphicsEffect(shadow)
        self.frame_level_6.setObjectName("frame_level_6")
        self.image_level_6 = QtWidgets.QLabel(self.frame_level_6)
        self.image_level_6.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.image_level_6.setText("")
        self.image_level_6.setPixmap(QtGui.QPixmap(
                folder_images_path.joinpath("уровень6.jpg").__str__()))
        self.image_level_6.setObjectName("image_level_6")
        self.name_level_6 = QtWidgets.QLabel(self.frame_level_6)
        self.name_level_6.setGeometry(QtCore.QRect(50, 120, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.name_level_6.setFont(font)
        self.name_level_6.setStyleSheet("color: rgb(42, 85, 126);\n"
"background-color: rgb(255, 177, 125);")
        self.name_level_6.setAlignment(QtCore.Qt.AlignCenter)
        self.name_level_6.setObjectName("name_level_6")
        self.stat_level_6 = QtWidgets.QFrame(self.frame_level_6)
        self.stat_level_6.setGeometry(QtCore.QRect(10, 229, 280, 111))
        self.stat_level_6.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.stat_level_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stat_level_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stat_level_6.setObjectName("stat_level_6")
        self.spedd_level_6 = QtWidgets.QLabel(self.stat_level_6)
        self.spedd_level_6.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.spedd_level_6.setFont(font)
        self.spedd_level_6.setStyleSheet("color: rgb(39, 117, 117);")
        self.spedd_level_6.setObjectName("spedd_level_6")
        self.count_accuracy_level_6 = QtWidgets.QProgressBar(self.stat_level_6)
        self.count_accuracy_level_6.setGeometry(QtCore.QRect(180, 70, 81, 23))
        self.count_accuracy_level_6.setStyleSheet("QProgressBar{\n"
"    color: rgb(255, 180, 130);\n"
"    border: 1px solid  grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(39, 117, 117);;\n"
"    border-radius: 3px;\n"
"}")
        self.count_accuracy_level_6.setProperty("value", 75)
        self.count_accuracy_level_6.setAlignment(QtCore.Qt.AlignCenter)
        self.count_accuracy_level_6.setOrientation(QtCore.Qt.Horizontal)
        self.count_accuracy_level_6.setFormat("%p%")
        self.count_accuracy_level_6.setObjectName("count_accuracy_level_6")
        self.accuracy_level_6 = QtWidgets.QLabel(self.stat_level_6)
        self.accuracy_level_6.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.accuracy_level_6.setFont(font)
        self.accuracy_level_6.setStyleSheet("color: rgb(39, 117, 117);")
        self.accuracy_level_6.setObjectName("accuracy_level_6")
        self.count_spedd_level_6 = QtWidgets.QLineEdit(self.stat_level_6)
        self.count_spedd_level_6.setGeometry(QtCore.QRect(180, 10, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.count_spedd_level_6.setFont(font)
        self.count_spedd_level_6.setStyleSheet("color: rgb(40, 120, 120);")
        self.count_spedd_level_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_spedd_level_6.setReadOnly(True)
        self.count_spedd_level_6.setObjectName("count_spedd_level_6")
        self.symbols_in_minute_level_6 = QtWidgets.QLabel(self.stat_level_6)
        self.symbols_in_minute_level_6.setGeometry(QtCore.QRect(210, 21, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.symbols_in_minute_level_6.setFont(font)
        self.symbols_in_minute_level_6.setStyleSheet("color: rgba(39, 117, 117, 120);")
        self.symbols_in_minute_level_6.setObjectName("symbols_in_minute_level_6")
        self.separator_level_6 = QtWidgets.QFrame(self.frame_level_6)
        self.separator_level_6.setGeometry(QtCore.QRect(10, 210, 280, 1))
        self.separator_level_6.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.separator_level_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_level_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_level_6.setObjectName("separator_level_6")
        self.button_level_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_level_6.setGeometry(QtCore.QRect(150, 500, 300, 350))
        self.button_level_6.setStyleSheet("QPushButton::hover{background-color : rgba(250, 250, 250, 30);}")
        self.button_level_6.setText("")
        self.button_level_6.setObjectName("button_level_6")
        self.frame_level_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_level_7.setGeometry(QtCore.QRect(480, 500, 300, 350))
        self.frame_level_7.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.frame_level_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_level_7.setFrameShadow(QtWidgets.QFrame.Raised)
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(50)
        self.frame_level_7.setGraphicsEffect(shadow)
        self.frame_level_7.setObjectName("frame_level_7")
        self.image_level_7 = QtWidgets.QLabel(self.frame_level_7)
        self.image_level_7.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.image_level_7.setText("")
        self.image_level_7.setPixmap(QtGui.QPixmap(
                folder_images_path.joinpath("уровень7.jpg").__str__()))
        self.image_level_7.setObjectName("image_level_7")
        self.name_level_7 = QtWidgets.QLabel(self.frame_level_7)
        self.name_level_7.setGeometry(QtCore.QRect(50, 120, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.name_level_7.setFont(font)
        self.name_level_7.setStyleSheet("color: rgb(42, 85, 126);\n"
"background-color: rgb(255, 177, 125);")
        self.name_level_7.setAlignment(QtCore.Qt.AlignCenter)
        self.name_level_7.setObjectName("name_level_7")
        self.stat_level_7 = QtWidgets.QFrame(self.frame_level_7)
        self.stat_level_7.setGeometry(QtCore.QRect(10, 229, 280, 111))
        self.stat_level_7.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.stat_level_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stat_level_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stat_level_7.setObjectName("stat_level_7")
        self.spedd_level_7 = QtWidgets.QLabel(self.stat_level_7)
        self.spedd_level_7.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.spedd_level_7.setFont(font)
        self.spedd_level_7.setStyleSheet("color: rgb(39, 117, 117);")
        self.spedd_level_7.setObjectName("spedd_level_7")
        self.count_accuracy_level_7 = QtWidgets.QProgressBar(self.stat_level_7)
        self.count_accuracy_level_7.setGeometry(QtCore.QRect(180, 70, 81, 23))
        self.count_accuracy_level_7.setStyleSheet("QProgressBar{\n"
"    color: rgb(255, 180, 130);\n"
"    border: 1px solid  grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(39, 117, 117);;\n"
"    border-radius: 3px;\n"
"}")
        self.count_accuracy_level_7.setProperty("value", 75)
        self.count_accuracy_level_7.setAlignment(QtCore.Qt.AlignCenter)
        self.count_accuracy_level_7.setOrientation(QtCore.Qt.Horizontal)
        self.count_accuracy_level_7.setFormat("%p%")
        self.count_accuracy_level_7.setObjectName("count_accuracy_level_7")
        self.accuracy_level_7 = QtWidgets.QLabel(self.stat_level_7)
        self.accuracy_level_7.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.accuracy_level_7.setFont(font)
        self.accuracy_level_7.setStyleSheet("color: rgb(39, 117, 117);")
        self.accuracy_level_7.setObjectName("accuracy_level_7")
        self.count_spedd_level_7 = QtWidgets.QLineEdit(self.stat_level_7)
        self.count_spedd_level_7.setGeometry(QtCore.QRect(180, 10, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.count_spedd_level_7.setFont(font)
        self.count_spedd_level_7.setStyleSheet("color: rgb(40, 120, 120);")
        self.count_spedd_level_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_spedd_level_7.setReadOnly(True)
        self.count_spedd_level_7.setObjectName("count_spedd_level_7")
        self.symbols_in_minute_level_7 = QtWidgets.QLabel(self.stat_level_7)
        self.symbols_in_minute_level_7.setGeometry(QtCore.QRect(210, 21, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.symbols_in_minute_level_7.setFont(font)
        self.symbols_in_minute_level_7.setStyleSheet("color: rgba(39, 117, 117, 120);")
        self.symbols_in_minute_level_7.setObjectName("symbols_in_minute_level_7")
        self.separator_level_7 = QtWidgets.QFrame(self.frame_level_7)
        self.separator_level_7.setGeometry(QtCore.QRect(10, 210, 280, 1))
        self.separator_level_7.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.separator_level_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_level_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_level_7.setObjectName("separator_level_7")
        self.button_level_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_level_7.setGeometry(QtCore.QRect(480, 500, 300, 350))
        self.button_level_7.setStyleSheet("QPushButton::hover{background-color : rgba(250, 250, 250, 30);}")
        self.button_level_7.setText("")
        self.button_level_7.setObjectName("button_level_7")
        self.frame_level_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_level_8.setGeometry(QtCore.QRect(810, 500, 300, 350))
        self.frame_level_8.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.frame_level_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_level_8.setFrameShadow(QtWidgets.QFrame.Raised)
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(50)
        self.frame_level_8.setGraphicsEffect(shadow)
        self.frame_level_8.setObjectName("frame_level_8")
        self.image_level_8 = QtWidgets.QLabel(self.frame_level_8)
        self.image_level_8.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.image_level_8.setText("")
        self.image_level_8.setPixmap(QtGui.QPixmap(
                folder_images_path.joinpath("уровень8.jpg").__str__()))
        self.image_level_8.setObjectName("image_level_8")
        self.name_level_8 = QtWidgets.QLabel(self.frame_level_8)
        self.name_level_8.setGeometry(QtCore.QRect(50, 120, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.name_level_8.setFont(font)
        self.name_level_8.setStyleSheet("color: rgb(42, 85, 126);\n"
"background-color: rgb(255, 177, 125);")
        self.name_level_8.setAlignment(QtCore.Qt.AlignCenter)
        self.name_level_8.setObjectName("name_level_8")
        self.stat_level_8 = QtWidgets.QFrame(self.frame_level_8)
        self.stat_level_8.setGeometry(QtCore.QRect(10, 229, 280, 111))
        self.stat_level_8.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.stat_level_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stat_level_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stat_level_8.setObjectName("stat_level_8")
        self.spedd_level_8 = QtWidgets.QLabel(self.stat_level_8)
        self.spedd_level_8.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.spedd_level_8.setFont(font)
        self.spedd_level_8.setStyleSheet("color: rgb(39, 117, 117);")
        self.spedd_level_8.setObjectName("spedd_level_8")
        self.count_accuracy_level_8 = QtWidgets.QProgressBar(self.stat_level_8)
        self.count_accuracy_level_8.setGeometry(QtCore.QRect(180, 70, 81, 23))
        self.count_accuracy_level_8.setStyleSheet("QProgressBar{\n"
"    color: rgb(255, 180, 130);\n"
"    border: 1px solid  grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(39, 117, 117);;\n"
"    border-radius: 3px;\n"
"}")
        self.count_accuracy_level_8.setProperty("value", 75)
        self.count_accuracy_level_8.setAlignment(QtCore.Qt.AlignCenter)
        self.count_accuracy_level_8.setOrientation(QtCore.Qt.Horizontal)
        self.count_accuracy_level_8.setFormat("%p%")
        self.count_accuracy_level_8.setObjectName("count_accuracy_level_8")
        self.accuracy_level_8 = QtWidgets.QLabel(self.stat_level_8)
        self.accuracy_level_8.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.accuracy_level_8.setFont(font)
        self.accuracy_level_8.setStyleSheet("color: rgb(39, 117, 117);")
        self.accuracy_level_8.setObjectName("accuracy_level_8")
        self.count_spedd_level_8 = QtWidgets.QLineEdit(self.stat_level_8)
        self.count_spedd_level_8.setGeometry(QtCore.QRect(180, 10, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.count_spedd_level_8.setFont(font)
        self.count_spedd_level_8.setStyleSheet("color: rgb(40, 120, 120);")
        self.count_spedd_level_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_spedd_level_8.setReadOnly(True)
        self.count_spedd_level_8.setObjectName("count_spedd_level_8")
        self.symbols_in_minute_level_8 = QtWidgets.QLabel(self.stat_level_8)
        self.symbols_in_minute_level_8.setGeometry(QtCore.QRect(210, 21, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.symbols_in_minute_level_8.setFont(font)
        self.symbols_in_minute_level_8.setStyleSheet("color: rgba(39, 117, 117, 120);")
        self.symbols_in_minute_level_8.setObjectName("symbols_in_minute_level_8")
        self.separator_level_8 = QtWidgets.QFrame(self.frame_level_8)
        self.separator_level_8.setGeometry(QtCore.QRect(10, 210, 280, 1))
        self.separator_level_8.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.separator_level_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_level_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_level_8.setObjectName("separator_level_8")
        self.button_level_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_level_8.setGeometry(QtCore.QRect(810, 500, 300, 350))
        self.button_level_8.setStyleSheet("QPushButton::hover{background-color : rgba(250, 250, 250, 30);}")
        self.button_level_8.setText("")
        self.button_level_8.setObjectName("button_level_8")
        self.frame_level_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_level_9.setGeometry(QtCore.QRect(1140, 500, 300, 350))
        self.frame_level_9.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.frame_level_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_level_9.setFrameShadow(QtWidgets.QFrame.Raised)
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(50)
        self.frame_level_9.setGraphicsEffect(shadow)
        self.frame_level_9.setObjectName("frame_level_9")
        self.image_level_9 = QtWidgets.QLabel(self.frame_level_9)
        self.image_level_9.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.image_level_9.setText("")
        self.image_level_9.setPixmap(QtGui.QPixmap(
                folder_images_path.joinpath("уровень9.jpg").__str__()))
        self.image_level_9.setObjectName("image_level_9")
        self.name_level_9 = QtWidgets.QLabel(self.frame_level_9)
        self.name_level_9.setGeometry(QtCore.QRect(50, 120, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.name_level_9.setFont(font)
        self.name_level_9.setStyleSheet("color: rgb(42, 85, 126);\n"
"background-color: rgb(255, 177, 125);")
        self.name_level_9.setAlignment(QtCore.Qt.AlignCenter)
        self.name_level_9.setObjectName("name_level_9")
        self.stat_level_9 = QtWidgets.QFrame(self.frame_level_9)
        self.stat_level_9.setGeometry(QtCore.QRect(10, 229, 280, 111))
        self.stat_level_9.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.stat_level_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stat_level_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stat_level_9.setObjectName("stat_level_9")
        self.spedd_level_9 = QtWidgets.QLabel(self.stat_level_9)
        self.spedd_level_9.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.spedd_level_9.setFont(font)
        self.spedd_level_9.setStyleSheet("color: rgb(39, 117, 117);")
        self.spedd_level_9.setObjectName("spedd_level_9")
        self.count_accuracy_level_9 = QtWidgets.QProgressBar(self.stat_level_9)
        self.count_accuracy_level_9.setGeometry(QtCore.QRect(180, 70, 81, 23))
        self.count_accuracy_level_9.setStyleSheet("QProgressBar{\n"
"    color: rgb(255, 180, 130);\n"
"    border: 1px solid  grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(39, 117, 117);;\n"
"    border-radius: 3px;\n"
"}")
        self.count_accuracy_level_9.setProperty("value", 75)
        self.count_accuracy_level_9.setAlignment(QtCore.Qt.AlignCenter)
        self.count_accuracy_level_9.setOrientation(QtCore.Qt.Horizontal)
        self.count_accuracy_level_9.setFormat("%p%")
        self.count_accuracy_level_9.setObjectName("count_accuracy_level_9")
        self.accuracy_level_9 = QtWidgets.QLabel(self.stat_level_9)
        self.accuracy_level_9.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.accuracy_level_9.setFont(font)
        self.accuracy_level_9.setStyleSheet("color: rgb(39, 117, 117);")
        self.accuracy_level_9.setObjectName("accuracy_level_9")
        self.count_spedd_level_9 = QtWidgets.QLineEdit(self.stat_level_9)
        self.count_spedd_level_9.setGeometry(QtCore.QRect(180, 10, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.count_spedd_level_9.setFont(font)
        self.count_spedd_level_9.setStyleSheet("color: rgb(40, 120, 120);")
        self.count_spedd_level_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_spedd_level_9.setReadOnly(True)
        self.count_spedd_level_9.setObjectName("count_spedd_level_9")
        self.symbols_in_minute_level_9 = QtWidgets.QLabel(self.stat_level_9)
        self.symbols_in_minute_level_9.setGeometry(QtCore.QRect(210, 21, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.symbols_in_minute_level_9.setFont(font)
        self.symbols_in_minute_level_9.setStyleSheet("color: rgba(39, 117, 117, 120);")
        self.symbols_in_minute_level_9.setObjectName("symbols_in_minute_level_9")
        self.separator_level_9 = QtWidgets.QFrame(self.frame_level_9)
        self.separator_level_9.setGeometry(QtCore.QRect(10, 210, 280, 1))
        self.separator_level_9.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.separator_level_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_level_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_level_9.setObjectName("separator_level_9")
        self.button_level_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_level_9.setGeometry(QtCore.QRect(1140, 500, 300, 350))
        self.button_level_9.setStyleSheet("QPushButton::hover{background-color : rgba(250, 250, 250, 30);}")
        self.button_level_9.setText("")
        self.button_level_9.setObjectName("button_level_9")
        self.frame_level_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_level_10.setGeometry(QtCore.QRect(1470, 500, 300, 350))
        self.frame_level_10.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.frame_level_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_level_10.setFrameShadow(QtWidgets.QFrame.Raised)
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(50)
        self.frame_level_10.setGraphicsEffect(shadow)
        self.frame_level_10.setObjectName("frame_level_10")
        self.image_level_10 = QtWidgets.QLabel(self.frame_level_10)
        self.image_level_10.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.image_level_10.setText("")
        self.image_level_10.setPixmap(QtGui.QPixmap(
                folder_images_path.joinpath("уровень10.jpg").__str__()))
        self.image_level_10.setObjectName("image_level_10")
        self.name_level_10 = QtWidgets.QLabel(self.frame_level_10)
        self.name_level_10.setGeometry(QtCore.QRect(50, 120, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.name_level_10.setFont(font)
        self.name_level_10.setStyleSheet("color: rgb(42, 85, 126);\n"
"background-color: rgb(255, 177, 125);")
        self.name_level_10.setAlignment(QtCore.Qt.AlignCenter)
        self.name_level_10.setObjectName("name_level_10")
        self.stat_level_10 = QtWidgets.QFrame(self.frame_level_10)
        self.stat_level_10.setGeometry(QtCore.QRect(10, 229, 280, 111))
        self.stat_level_10.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.stat_level_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stat_level_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stat_level_10.setObjectName("stat_level_10")
        self.spedd_level_10 = QtWidgets.QLabel(self.stat_level_10)
        self.spedd_level_10.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.spedd_level_10.setFont(font)
        self.spedd_level_10.setStyleSheet("color: rgb(39, 117, 117);")
        self.spedd_level_10.setObjectName("spedd_level_10")
        self.count_accuracy_level_10 = QtWidgets.QProgressBar(self.stat_level_10)
        self.count_accuracy_level_10.setGeometry(QtCore.QRect(180, 70, 81, 23))
        self.count_accuracy_level_10.setStyleSheet("QProgressBar{\n"
"    color: rgb(255, 180, 130);\n"
"    border: 1px solid  grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(39, 117, 117);;\n"
"    border-radius: 3px;\n"
"}")
        self.count_accuracy_level_10.setProperty("value", 75)
        self.count_accuracy_level_10.setAlignment(QtCore.Qt.AlignCenter)
        self.count_accuracy_level_10.setOrientation(QtCore.Qt.Horizontal)
        self.count_accuracy_level_10.setFormat("%p%")
        self.count_accuracy_level_10.setObjectName("count_accuracy_level_10")
        self.accuracy_level_10 = QtWidgets.QLabel(self.stat_level_10)
        self.accuracy_level_10.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.accuracy_level_10.setFont(font)
        self.accuracy_level_10.setStyleSheet("color: rgb(39, 117, 117);")
        self.accuracy_level_10.setObjectName("accuracy_level_10")
        self.count_spedd_level_10 = QtWidgets.QLineEdit(self.stat_level_10)
        self.count_spedd_level_10.setGeometry(QtCore.QRect(180, 10, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.count_spedd_level_10.setFont(font)
        self.count_spedd_level_10.setStyleSheet("color: rgb(40, 120, 120);")
        self.count_spedd_level_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_spedd_level_10.setReadOnly(True)
        self.count_spedd_level_10.setObjectName("count_spedd_level_10")
        self.symbols_in_minute_level_10 = QtWidgets.QLabel(self.stat_level_10)
        self.symbols_in_minute_level_10.setGeometry(QtCore.QRect(210, 21, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.symbols_in_minute_level_10.setFont(font)
        self.symbols_in_minute_level_10.setStyleSheet("color: rgba(39, 117, 117, 120);")
        self.symbols_in_minute_level_10.setObjectName("symbols_in_minute_level_10")
        self.separator_level_10 = QtWidgets.QFrame(self.frame_level_10)
        self.separator_level_10.setGeometry(QtCore.QRect(10, 210, 280, 1))
        self.separator_level_10.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.separator_level_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_level_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_level_10.setObjectName("separator_level_10")
        self.button_level_10 = QtWidgets.QPushButton(self.centralwidget)
        self.button_level_10.setGeometry(QtCore.QRect(1470, 500, 300, 350))
        self.button_level_10.setStyleSheet("QPushButton::hover{background-color : rgba(250, 250, 250, 30);}")
        self.button_level_10.setText("")
        self.button_level_10.setObjectName("button_level_10")
        self.name_go_home = QtWidgets.QLabel(self.centralwidget)
        self.name_go_home.setGeometry(QtCore.QRect(770, 900, 371, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.name_go_home.setFont(font)
        self.name_go_home.setStyleSheet("color: rgb(42, 85, 126);\n"
"background-color: rgb(255, 177, 125);")
        self.name_go_home.setAlignment(QtCore.Qt.AlignCenter)
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(50)
        self.name_go_home.setGraphicsEffect(shadow)
        self.name_go_home.setObjectName("name_go_home")
        self.button_go_home = QtWidgets.QPushButton(self.centralwidget)
        self.button_go_home.setGeometry(QtCore.QRect(770, 900, 370, 60))
        self.button_go_home.setStyleSheet("QPushButton::hover{background-color : rgba(250, 250, 250, 30);}\n"
"")
        self.button_go_home.setText("")
        self.button_go_home.setObjectName("button_go_home")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_level_1.setText(_translate("MainWindow", "Уровень 1"))
        self.spedd_level_1.setText(_translate("MainWindow", "Лучшая скорость"))
        self.accuracy_level_1.setText(_translate("MainWindow", "Лучшая точность"))
        self.count_spedd_level_1.setText(_translate("MainWindow", "99"))
        self.symbols_in_minute_level_1.setText(_translate("MainWindow", "(слов)"))
        self.name_level_2.setText(_translate("MainWindow", "Уровень 2"))
        self.spedd_level_2.setText(_translate("MainWindow", "Лучшая скорость"))
        self.accuracy_level_2.setText(_translate("MainWindow", "Лучшая точность"))
        self.count_spedd_level_2.setText(_translate("MainWindow", "99"))
        self.symbols_in_minute_level_2.setText(_translate("MainWindow", "(слов)"))
        self.name_level_3.setText(_translate("MainWindow", "Уровень 3"))
        self.spedd_level_3.setText(_translate("MainWindow", "Лучшая скорость"))
        self.accuracy_level_3.setText(_translate("MainWindow", "Лучшая точность"))
        self.count_spedd_level_3.setText(_translate("MainWindow", "99"))
        self.symbols_in_minute_level_3.setText(_translate("MainWindow", "(слов)"))
        self.name_level_4.setText(_translate("MainWindow", "Уровень 4"))
        self.spedd_level_4.setText(_translate("MainWindow", "Лучшая скорость"))
        self.accuracy_level_4.setText(_translate("MainWindow", "Лучшая точность"))
        self.count_spedd_level_4.setText(_translate("MainWindow", "99"))
        self.symbols_in_minute_level_4.setText(_translate("MainWindow", "(слов)"))
        self.name_level_5.setText(_translate("MainWindow", "Уровень 5"))
        self.spedd_level_5.setText(_translate("MainWindow", "Лучшая скорость"))
        self.accuracy_level_5.setText(_translate("MainWindow", "Лучшая точность"))
        self.count_spedd_level_5.setText(_translate("MainWindow", "99"))
        self.symbols_in_minute_level_5.setText(_translate("MainWindow", "(слов)"))
        self.name_level_6.setText(_translate("MainWindow", "Уровень 6"))
        self.spedd_level_6.setText(_translate("MainWindow", "Лучшая скорость"))
        self.accuracy_level_6.setText(_translate("MainWindow", "Лучшая точность"))
        self.count_spedd_level_6.setText(_translate("MainWindow", "99"))
        self.symbols_in_minute_level_6.setText(_translate("MainWindow", "(слов)"))
        self.name_level_7.setText(_translate("MainWindow", "Уровень 7"))
        self.spedd_level_7.setText(_translate("MainWindow", "Лучшая скорость"))
        self.accuracy_level_7.setText(_translate("MainWindow", "Лучшая точность"))
        self.count_spedd_level_7.setText(_translate("MainWindow", "99"))
        self.symbols_in_minute_level_7.setText(_translate("MainWindow", "(слов)"))
        self.name_level_8.setText(_translate("MainWindow", "Уровень 8"))
        self.spedd_level_8.setText(_translate("MainWindow", "Лучшая скорость"))
        self.accuracy_level_8.setText(_translate("MainWindow", "Лучшая точность"))
        self.count_spedd_level_8.setText(_translate("MainWindow", "99"))
        self.symbols_in_minute_level_8.setText(_translate("MainWindow", "(слов)"))
        self.name_level_9.setText(_translate("MainWindow", "Уровень 9"))
        self.spedd_level_9.setText(_translate("MainWindow", "Лучшая скорость"))
        self.accuracy_level_9.setText(_translate("MainWindow", "Лучшая точность"))
        self.count_spedd_level_9.setText(_translate("MainWindow", "99"))
        self.symbols_in_minute_level_9.setText(_translate("MainWindow", "(слов)"))
        self.name_level_10.setText(_translate("MainWindow", "Уровень 10"))
        self.spedd_level_10.setText(_translate("MainWindow", "Лучшая скорость"))
        self.accuracy_level_10.setText(_translate("MainWindow", "Лучшая точность"))
        self.count_spedd_level_10.setText(_translate("MainWindow", "99"))
        self.symbols_in_minute_level_10.setText(_translate("MainWindow", "(слов)"))
        self.name_go_home.setText(_translate("MainWindow", "На главное меню"))
